### PR TITLE
:sparkles: android endpoints for mobile

### PR DESCRIPTION
**Pull request by jlandure**

### CODE REVIEW

**Review by bpetetot — APPROVED** [review]
yeah !!!

**Comment by cyrilmottier** [comment]
So if I read correctly the code – I'm no expert in cloud functions nor JS – you're, like Trump, saying "fuck COP21", right? Indeed, each time a client `GET /api/v1/schedule`, you recompute the whole JSON and decide whether to respond with 200 or 304 depending on the computation.

Maybe, one day, you'll make sure data has changed before starting recomputing everything and cache the computation to prevent useless computations :trollface:

https://www.makeourplanetgreatagain.fr/

**Comment by jlandure** [comment]
Yes this is the next version! using cloud storage to store the computation 💃

**Comment by cyrilmottier** [comment]
Nice ❤️

**Pull request merged**
